import { Badge, Notice, Panel } from '../components/layout'

export function MessagesPage({ t }: { t: (key: string) => string }) {
  return <div className="grid main-2"><Panel title={t('notification_center')} desc={t('notification_center_desc')}><div className="table-list">{['KYC status updated to Approved','Quote Q-20260406-119 will expire in 15 seconds','Withdrawal WD-20260406-018 moved to Awaiting On-chain Confirmation','System notice: BTC withdrawals temporarily under degraded mode'].map((msg,idx) => <div className="card-block" key={msg}><div className="row-between"><strong>Notification #{idx+1}</strong><Badge text="Visible" tone="info" /></div><div className="meta" style={{marginTop:8}}>{msg}</div></div>)}</div></Panel><Panel title={t('status_design')} desc={t('status_design_body_1')}><div className="table-list">{[t('status_design_body_1'),t('status_design_body_2')].map(x => <div className="card-block hero-note" key={x}>• {x}</div>)}</div></Panel></div>
}

export function ChatPage({ t }: { t: (key: string) => string }) {
  return <div className="grid main-3"><Panel title={t('conversation_list')} desc={t('conversation_list_desc')}><div className="table-list">{['BTC Large Quote Assistance','Withdrawal Delay Inquiry','KYC Review Follow-up'].map(x => <div className="card-block" key={x}>{x}</div>)}</div></Panel><Panel title={t('trader_chat_title')} desc={t('trader_chat_desc')}><Notice title={t('formal_flow_required')} body={t('formal_flow_required_body')} /><div className="table-list" style={{marginTop:14}}><div className="card-block">{t('chat_sample_1')}</div><div className="card-block" style={{background:'#16314F', borderColor:'rgba(59,167,255,0.22)'}}>{t('chat_sample_2')}</div></div><div className="button-row" style={{marginTop:14}}><input className="search-box" style={{flex:1, minWidth:0}} placeholder={t('chat_placeholder')} /><button className="btn">{t('send')}</button></div></Panel></div>
}

export function TeamPage({ t }: { t: (key: string) => string }) {
  return <div className="grid main-3"><Panel title={t('team')} desc={t('team_access_desc')}><div className="table-list">{[['admin.finance@payso.io','admin','All Accounts'],['operator.otc@payso.io','operator','OTC Desk A'],['approver.ops@payso.io','approver','Withdrawals Only']].map(([email,r,scope]) => <div className="table-row" key={email}><div><div className="value" style={{marginTop:0}}>{email}</div></div><div><div className="value" style={{marginTop:0}}>{r}</div></div><div style={{justifySelf:'end'}}><span className="meta">{scope}</span></div></div>)}</div></Panel><Panel title={t('invite_member')} desc={t('team_access_desc')}><div className="form-grid"><input className="input full" placeholder={t('member_email')} /><input className="input" placeholder={t('role_placeholder')} /><input className="input" placeholder={t('account_scope')} /></div><button className="btn" style={{marginTop:14}}>{t('send_invitation')}</button></Panel></div>
}
