import { Badge, Notice, Panel } from '../components/layout'

export function WithdrawPage({ t, setPage, setModal }: { t: (key: string) => string; setPage: (page: any) => void; setModal: (m: any) => void }) {
  return <div className="grid main-3"><Panel title={t('withdrawal_form')} desc={t('withdrawal_form_desc')}><div className="form-grid"><input className="input" defaultValue="USDT" /><input className="input" defaultValue="TRON" /><input className="input" defaultValue="120000" /><input className="input" defaultValue="Approved Settlement Wallet" /></div><div className="grid cols-2" style={{marginTop:14}}><div className="card-block"><div className="label">{t('available_balance')}</div><div className="value">820,000 USDT</div></div><div className="card-block"><div className="label">{t('destination_status')}</div><div className="value">{t('approved_address')}</div></div></div><div style={{marginTop:14}}><Notice title={t('approval_required')} body={t('approval_required_body')} /></div><input className="input" type="password" placeholder={t('enter_operator_pin')} style={{marginTop:14}} /><button className="btn" style={{width:'100%', marginTop:14}} onClick={() => setModal('submitWithdrawal')}>{t('submit_request')}</button></Panel><Panel title={t('recent_withdrawals')} desc={t('recent_withdrawals_desc')}><div className="table-list">{[['WD-001','Approval Pending','Not Broadcast','warning'],['WD-002','Approved','Pending On-chain','info'],['WD-003','Approved','Completed','success']].map(([id,approval,transfer,tone]) => <button className="table-row" key={id} onClick={() => setPage('withdraw_tracking')}><div><div className="value" style={{marginTop:0}}>{id}</div><div className="meta">Approval: {approval} · Transfer: {transfer}</div></div><div /><div style={{justifySelf:'end'}}><Badge text={transfer} tone={tone as any} /></div></button>)}</div></Panel></div>
}

export function WithdrawSubmittedPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <Panel title={t('request_submitted')} desc={t('request_submitted_body')}><div className="grid cols-2">{[[t('request_id'),'WD-20260406-018'],[t('amount'),'120,000 USDT'],[t('next_step'),t('awaiting_approver')]].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div><div className="button-row" style={{marginTop:14}}><button className="btn" onClick={() => setPage('withdraw_tracking')}>{t('view_request_status')}</button><button className="btn secondary" onClick={() => setPage('withdraw')}>{t('back_to_withdraw')}</button></div></Panel>
}

export function WithdrawTrackingPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <div className="grid main-2"><Panel title={t('withdrawal_tracking')} desc={t('withdrawal_tracking_desc')}><div className="grid cols-2">{[[t('submitted_by'),'operator.otc@payso.io'],[t('approved_by'),'approver.ops@payso.io']].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div><div className="grid cols-2" style={{marginTop:16}}><div><div className="section-title">{t('approval_line')}</div><div className="timeline">{[['10:14:22','Withdrawal request created','Ref: WD-20260406-018 · source account locked for review scope','neutral'],['10:15:09','Risk result attached','Ref: RISK-7721 · amount threshold matched, approval still required','warning'],['10:18:44','Approval confirmed','Ref: APR-5512 · approver note retained','success']].map(([time,title,detail,tone]) => <div className="timeline-row" key={time+title}><div className="time">{time}</div><div><div className="event-title">{title}</div><div className="event-detail">{detail}</div></div><div style={{textAlign:'right'}}><Badge text={tone === 'success' ? 'Recorded' : tone === 'warning' ? 'Review' : 'Observed'} tone={tone as any} /></div></div>)}</div></div><div><div className="section-title">{t('transfer_line')}</div><div className="timeline">{[['10:18:51','Broadcast request queued','Ref: CST-2011 · custody handoff accepted','info'],['10:19:04','Broadcast observed','tx_hash: 0x8f...d22 · pending confirmations','info'],['10:24:17',t('confirming_onchain'),'8 / 20 confirmations observed','warning']].map(([time,title,detail,tone]) => <div className="timeline-row" key={time+title}><div className="time">{time}</div><div><div className="event-title">{title}</div><div className="event-detail">{detail}</div></div><div style={{textAlign:'right'}}><Badge text={tone === 'warning' ? 'Review' : 'Confirmed'} tone={tone as any} /></div></div>)}</div></div></div></Panel><Panel title={t('request_summary')} desc="This request has already passed approval. The remaining path is broadcast outcome and on-chain completion."><div className="table-list">{['Approval state: Approved','Broadcast state: Sent to custody','On-chain state: 8 / 20 confirmations','Ledger posture: pending_onchain / network fee reserved'].map(x => <div className="card-block hero-note" key={x}>• {x}</div>)}</div><button className="btn secondary" style={{width:'100%', marginTop:12}} onClick={() => setPage('approvals')}>{t('open_approvals')}</button></Panel></div>
}

export function ApprovalsPage({ t, setPage, setModal }: { t: (key: string) => string; setPage: (page: any) => void; setModal: (m: any) => void }) {
  return <div className="grid main-2"><Panel title={t('approval_queue')} desc={t('approval_queue_desc')}><div className="button-row" style={{marginBottom:14}}><button className="btn secondary">{t('address_requests')}</button><button className="btn">{t('withdrawal_requests')}</button><button className="btn ghost" onClick={() => setPage('approval_history')}>{t('history')}</button></div><div className="table-list">{[['APR-WD-001','Withdrawal','120,000 USDT','High','operator.otc@payso.io'],['APR-AD-002','Address','TRON / Settlement Wallet','Medium','ops.user@payso.io']].map(([id,type,detail,risk,actor]) => <button className="table-row" key={id} onClick={() => setPage(type === 'Address' ? 'address_approval_detail' : 'approvals')}><div><div className="value" style={{marginTop:0}}>{id}</div><div className="meta">{type} · {detail} · Risk {risk} · by {actor}</div></div><div /><div style={{justifySelf:'end'}}><Badge text="Open" tone="warning" /></div></button>)}</div></Panel><Panel title={t('approval_detail')} desc={t('approval_detail_desc')}><div className="grid cols-2">{[[t('approval_type'),'Withdrawal Request'],[t('source_account'),'OTC Desk A']].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div><div style={{marginTop:14}}><Notice title={t('decision_required')} body={t('decision_required_body')} /></div><div className="grid cols-2" style={{marginTop:14}}><div className="card-block">Risk Decision: REVIEW_REQUIRED</div><div className="card-block">Limit Result: within configured hard ceiling</div></div><input className="input" placeholder={t('decision_note')} style={{marginTop:14}} /><div className="button-row" style={{marginTop:14}}><button className="btn" onClick={() => setModal('approveWithdrawal')}>{t('approve_request')}</button><button className="btn secondary">{t('reject_request')}</button></div><button className="btn ghost" style={{width:'100%', marginTop:12}} onClick={() => setPage('approval_history')}>{t('approval_history')}</button></Panel></div>
}

export function ApprovalHistoryPage({ t }: { t: (key: string) => string }) {
  return <Panel title={t('approval_history')} desc={t('approval_history_desc')}><div className="table-list">{[['APR-WD-221','Withdrawal','Approved','2026-04-06 10:14','AUD-REF-44'],['APR-AD-119','Address','Rejected','2026-04-05 18:22','AUD-REF-31'],['APR-WD-214','Withdrawal','Approved','2026-04-05 14:08','AUD-REF-27']].map(([id,obj,result,time,ref]) => <div className="table-row" key={id}><div><div className="label">{t('approval_id')}</div><div className="value">{id}</div></div><div><div className="label">{t('related_object')}</div><div className="value">{obj}</div></div><div style={{justifySelf:'end'}}><Badge text={result} tone={result === 'Approved' ? 'success' : 'danger'} /></div><div><div className="label">{t('decision_time')}</div><div className="value">{time}</div></div><div><div className="label">Reference</div><div className="value">{ref}</div></div></div>)}</div></Panel>
}

export function AddressBookPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <div className="grid main-3"><Panel title={t('address_book')} desc={t('address_book_desc')}><div className="table-list">{[['Approved Settlement Wallet','USDT / TRON','Approved','active'],['Treasury Cold Wallet','BTC / Bitcoin','Approved','active'],['New Ops Wallet Request','ETH / Ethereum','Pending','deprecated']].map(([label,assetChain,status,lifecycle]) => <div className="table-row" key={label}><div><div className="value" style={{marginTop:0}}>{label}</div><div className="meta">{t('asset_chain')}: {assetChain} · lifecycle: {lifecycle}</div></div><div /><div style={{justifySelf:'end'}}><Badge text={status} tone={status === 'Approved' ? 'success' : 'warning'} /></div></div>)}</div></Panel><Panel title={t('usage_note')} desc={t('usage_note_body')}><div className="table-list">{['Operators may submit new destination requests, but they cannot use those destinations until approval is complete.','Address status, lifecycle state, and assignment evidence must remain auditable for ops, finance, and investigation views.'].map(x => <div className="card-block hero-note" key={x}>• {x}</div>)}</div><button className="btn" style={{width:'100%', marginTop:12}} onClick={() => setPage('add_address')}>{t('add_new_address')}</button></Panel></div>
}

export function AddAddressPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <div className="grid main-3"><Panel title={t('add_new_address_title')} desc={t('add_new_address_desc')}><div className="form-grid"><input className="input" placeholder={t('address_label')} /><input className="input" defaultValue="USDT / TRON" /><input className="input full" placeholder={t('destination_address')} /><input className="input full" placeholder={t('request_reason')} /></div><button className="btn" style={{marginTop:14}} onClick={() => setPage('address_approval_detail')}>{t('create_request')}</button></Panel><Panel title={t('validation_summary')} desc={t('validation_summary_desc')}><div className="table-list">{['Address format validation: passed','Network compatibility: TRON / USDT','Final usability posture: pending approver decision'].map(x => <div className="card-block hero-note" key={x}>• {x}</div>)}</div></Panel></div>
}

export function AddressApprovalDetailPage({ t, setModal }: { t: (key: string) => string; setModal: (m: any) => void }) {
  return <Panel title={t('address_approval_detail')} desc={t('address_approval_detail_desc')}><div className="grid cols-2">{[[t('address_label'),'Settlement Wallet B'],[t('asset_chain'),'USDT / TRON'],['Risk','Low']].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div><div style={{marginTop:14}}><Notice title={t('address_approver_required')} body={t('address_approver_required_body')} /></div><div className="grid cols-2" style={{marginTop:14}}><div className="card-block">assignment_evidence_ref: ADDR-ASSIGN-882</div><div className="card-block">wallet_domain: treasury_withdrawal_domain</div></div><div className="button-row" style={{marginTop:14}}><button className="btn" onClick={() => setModal('approveAddress')}>{t('approve_address')}</button><button className="btn secondary">{t('reject_address')}</button></div></Panel>
}
