import { Badge, Metric, Notice, Panel } from '../components/layout'

export function DashboardPage({ t }: { t: (key: string) => string }) {
  return <div className="grid"><div className="grid cols-4"><Metric title={t('portfolio_value')} value="$2.48M" sub={t('plus_today')} /><Metric title={t('available_to_trade')} value="$1.72M" sub={t('across_assets')} /><Metric title={t('pending_deposit')} value="$148K" sub={t('waiting_confirmations')} /><Metric title={t('withdrawal_queue')} value="3" sub={t('requests_needs_review')} /></div><div className="grid main-2"><Panel title={t('asset_overview')} desc={t('asset_overview_desc')}><div className="table-list">{[['USDT','$840,000','$120,000','$36,000'],['BTC','$620,000','$48,000','$0'],['ETH','$540,000','$30,000','$14,000']].map(([a,av,fr,pr]) => <div className="card-block" key={a}><div className="row-between"><strong>{a}</strong><Badge text="Ledger Anchored" tone="info" /></div><div className="grid cols-2" style={{marginTop:12}}><div><div className="label">{t('available')}</div><div className="value">{av}</div></div><div><div className="label">{t('frozen')}</div><div className="value">{fr}</div></div><div><div className="label">{t('processing')}</div><div className="value">{pr}</div></div></div></div>)}</div></Panel><div className="grid"><Panel title="System Mode & Connectivity" desc="Runtime control posture across pricing, execution, custody, and notifications."><div className="table-list">{[['System Mode','Normal','success'],['LP Connectivity','Healthy','success'],['Custody Connectivity','Healthy','success'],['Notification Delivery','Monitored','info']].map(([k,v,tone]) => <div className="row-between card-block" key={k}><span>{k}</span><Badge text={v} tone={tone as any} /></div>)}</div></Panel><Panel title="Risk & Approval Summary" desc="Designed for management review and operational oversight."><div className="table-list">{['1 withdrawal request currently requires enhanced review due to amount threshold.','0 address approval requests are currently blocked by sanctions or wallet-domain restrictions.','Quote TTL remains aligned to controlled default policy and is centrally configurable.'].map(x => <div className="card-block hero-note" key={x}>• {x}</div>)}</div></Panel></div></div></div>
}

export function KycPage({ t }: { t: (key: string) => string }) {
  return <div className="grid main-3"><Panel title={t('kyc_flow')} desc={t('kyc_flow_desc')}><div className="table-list">{[[t('registration'),t('completed'),'Provider case initiated and client identity subject created.'],[t('identity_verification'),t('approved'),'Identity provider result normalized into internal access state.'],[t('suitability'),t('approved'),'Client suitability tier permits controlled spot trading access.'],[t('risk_disclosure'),t('accepted'),'Risk disclosure confirmation retained as auditable evidence.']].map(([label,status,desc]) => <div className="card-block" key={label}><div className="row-between"><strong>{label}</strong><Badge text={status} tone="success" /></div><div className="meta" style={{marginTop:8}}>{desc}</div></div>)}</div></Panel><Panel title={t('client_profile')} desc={t('access_enabled_body')}><div className="table-list">{['KYC Status: Approved','Suitability Tier: Spot Trading','can_trade = true','can_withdraw = true'].map(x => <div className="card-block" key={x}>{x}</div>)}</div><div style={{marginTop:14}}><Notice title={t('access_enabled')} body={t('access_enabled_body')} /></div></Panel></div>
}

export function AccountsPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <Panel title={t('accounts')} desc={t('view_accounts_desc')}><div className="button-row" style={{marginBottom:14}}><input className="search-box" placeholder={t('search_account')} /><button className="btn ghost">{t('filters')}</button><button className="btn ghost">{t('refresh_visibility')}</button></div><div className="table-list">{[['Treasury Main','Institution Main','USDT / BTC / ETH','2','$1.84M'],['OTC Desk A','Sub-account','USDT / BTC','1','$420K'],['Settlement Buffer','Sub-account','USDC / PHPC','0','$210K']].map(([name,type,assets,pending,balance]) => <button className="table-row" key={name} onClick={() => setPage('account_detail')}><div><div className="value" style={{marginTop:0}}>{name}</div><div className="meta">{t('type')}: {type} · Assets: {assets} · Balance: {balance}</div></div><div /><div style={{justifySelf:'end'}}><Badge text={`${t('pending_approvals')}: ${pending}`} tone={pending === '0' ? 'neutral' : 'warning'} /></div></button>)}</div></Panel>
}

export function AccountDetailPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <div className="grid main-3"><Panel title={t('account_detail')} desc={t('account_detail_desc')}><div className="grid cols-2">{[['USDT','820,000'],['BTC','11.42'],['ETH','93.8']].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div><div className="grid cols-2" style={{marginTop:14}}><div className="card-block">Restriction Status: None</div><div className="card-block">Approval Exposure: 2 open items</div></div><div className="card-block hero-note" style={{marginTop:14}}>Institution main account can aggregate balances from visible sub-accounts. Address, transfer, and ledger views can all drill down to sub-account granularity without losing audit references.</div></Panel><Panel title={t('quick_actions')} desc="Action entry points remain controlled and do not bypass authorization, risk, approval, or ledger flows."><div className="table-list"><button className="btn" onClick={() => setPage('deposit')}>{t('view_deposit_address')}</button><button className="btn" onClick={() => setPage('trade')}>{t('start_rfq_trade')}</button><button className="btn" onClick={() => setPage('withdraw')}>{t('create_withdrawal_request')}</button><button className="btn secondary" onClick={() => setPage('orders')}>{t('view_orders')}</button><button className="btn secondary" onClick={() => setPage('address_book')}>{t('open_address_book')}</button></div></Panel></div>
}

export function DepositPage({ t }: { t: (key: string) => string }) {
  return <div className="grid main-3"><Panel title={t('deposit_address')} desc={t('deposit_desc')}><div className="grid cols-2"><div className="card-block"><div className="label">{t('asset')}</div><div className="value">USDT</div></div><div className="card-block"><div className="label">{t('network')}</div><div className="value">TRON</div></div></div><div className="card-block" style={{marginTop:14, borderColor:'rgba(59,167,255,0.22)'}}><div className="section-title">{t('assigned_deposit_address')}</div><div className="value" style={{fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace'}}>TVjs8N8f8R9x6PxDemoAddressForPrototypeOnly123</div><div className="button-row" style={{marginTop:14}}><button className="btn">{t('copy_address')}</button><button className="btn secondary">{t('show_qr')}</button></div></div></Panel><Panel title={t('deposit_instructions')} desc={t('deposit_instructions_desc')}><Notice title="Display address is not a credit fact" body={t('deposit_instructions_desc')} /><div className="table-list">{['1. Transfer only through supported networks.','2. Final credit depends on on-chain detection, confirmations, and ledger posting.','3. Funds arriving through deprecated or abnormal routes enter controlled exception handling.'].map(x => <div className="card-block hero-note" key={x}>{x}</div>)}</div></Panel></div>
}
