import { Badge, Notice, Panel } from '../components/layout'

export function TradePage({ t, setModal }: { t: (key: string) => string; setModal: (m: any) => void }) {
  return <div className="grid main-3"><Panel title={t('quote_request')} desc={t('quote_request_desc')}><div className="button-row" style={{marginBottom:14}}><button className="btn">{t('buy')}</button><button className="btn secondary">{t('sell')}</button></div><div className="form-grid"><input className="input" defaultValue="USDT" /><input className="input" defaultValue="BTC" /><input className="input" defaultValue="250000" /><button className="btn">{t('request_quote')}</button></div></Panel><Panel title={t('quote_confirmation')} desc={t('quote_confirmation_desc')}><div className="card-block" style={{borderColor:'rgba(59,167,255,0.22)'}}><div className="row-between"><span className="meta">{t('live_quote')}</span><Badge text={`${t('ttl')}: 00:52`} tone="info" /></div><div className="table-list" style={{marginTop:12}}><div className="row-between"><span>250,000 USDT</span><strong>→ 3.582 BTC</strong></div><div className="row-between"><span>{t('fee')}</span><strong>250 USDT</strong></div><div className="row-between"><span>{t('quote_rate')}</span><strong>69,742.11</strong></div></div></div><div style={{marginTop:14}}><Notice title={t('formal_confirmation_required')} body={t('formal_confirmation_required_body')} /></div><input className="input" type="password" placeholder={t('enter_trading_pin')} style={{marginTop:14}} /><button className="btn" style={{width:'100%', marginTop:14}} onClick={() => setModal('confirmTrade')}>{t('confirm_quote')}</button></Panel></div>
}

export function OrdersPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <Panel title={t('orders')} desc={t('orders_desc')}><div className="button-row" style={{marginBottom:14}}><input className="search-box" placeholder={t('search_order')} /><button className="btn ghost">{t('saved_views')}</button></div><div className="table-list">{[['ORD-240318-001','USDT/BTC','Filled','Operator A','ROUTE-1 / LP-A','success'],['ORD-240318-002','BTC/USDC','Executing','Client Web','ROUTE-2 / LP-B','info'],['ORD-240318-003','ETH/USDT','Partially Filled','Client App','ROUTE-1 / LP-A','warning']].map(([id,pair,status,who,route,tone]) => <button className="table-row" key={id} onClick={() => setPage('order_detail')}><div><div className="value" style={{marginTop:0}}>{id}</div><div className="meta">{t('pair')}: {pair} · {t('initiated_by')}: {who} · {route}</div></div><div /><div style={{justifySelf:'end'}}><Badge text={status} tone={tone as any} /></div></button>)}</div></Panel>
}

export function OrderDetailPage({ t, setPage }: { t: (key: string) => string; setPage: (page: any) => void }) {
  return <div className="grid main-2"><div className="grid"><Panel title={t('order_detail')} desc={t('order_detail_desc')}><div className="grid cols-2">{[[t('pair'),'USDT / BTC'],[t('authorization'),'AUTH-20260406-021 / Confirmed'],[t('source_amount'),'250,000 USDT'],[t('target_amount'),'3.582 BTC'],[t('fee'),'250 USDT'],[t('quote_rate'),'69,742.11']].map(([k,v]) => <div className="card-block" key={k}><div className="label">{k}</div><div className="value">{v}</div></div>)}</div></Panel><Panel title="Authorization Evidence" desc="Formal authorization remains a distinct object and does not collapse into order creation or execution events."><div className="grid cols-2">{['session_id: SES-331-AX','device_context: web/chrome/us-west','auth_method: PIN + MFA session','confirmed_at: 2026-04-06 10:41:12'].map(x => <div className="card-block" key={x}>{x}</div>)}</div></Panel></div><Panel title={t('status_timeline')} desc="Event-by-event audit-oriented trace with reference posture."><div className="timeline">{[['2026-04-06 10:41:12',t('authorization_confirmed'),'Ref: AUTH-20260406-021 · quote consumed within valid TTL','info'],['2026-04-06 10:41:13',t('order_created'),'Ref: ORD-240318-001 · freeze reference bound successfully','success'],['2026-04-06 10:41:14',t('execution_request_sent'),'Ref: EXEC-0193 · routing policy version P-7 applied','info'],['2026-04-06 10:41:17',t('fill_received'),'Ref: FILL-8821 · normalized from LP response','success'],['2026-04-06 10:41:18',t('status_updated'),'Client-visible order state updated after execution mapping','neutral']].map(([time,title,detail,tone]) => <div className="timeline-row" key={time + title}><div className="time">{time}</div><div><div className="event-title">{title}</div><div className="event-detail">{detail}</div></div><div style={{textAlign:'right'}}><Badge text={tone === 'success' ? 'Recorded' : tone === 'info' ? 'Confirmed' : 'Observed'} tone={tone as any} /></div></div>)}</div><button className="btn secondary" style={{width:'100%', marginTop:12}} onClick={() => setPage('accounts')}>{t('accounts')}</button></Panel></div>
}
