export type Role = 'client' | 'admin' | 'operator' | 'approver'
export type UiMode = 'normal' | 'loading' | 'empty' | 'error'
export type Language = 'zh' | 'en'
export type ModalType = null | 'submitWithdrawal' | 'approveWithdrawal' | 'approveAddress' | 'confirmTrade'
export type Page =
  | 'dashboard'
  | 'kyc'
  | 'accounts'
  | 'account_detail'
  | 'deposit'
  | 'trade'
  | 'orders'
  | 'order_detail'
  | 'withdraw'
  | 'withdraw_submitted'
  | 'withdraw_tracking'
  | 'approvals'
  | 'approval_history'
  | 'address_book'
  | 'add_address'
  | 'address_approval_detail'
  | 'team'
  | 'messages'
  | 'chat'
  | 'admin_console'
  | 'admin_users'
  | 'admin_monitoring'
  | 'admin_risk'
  | 'admin_ledger'
  | 'admin_liquidity'
  | 'admin_settings'

export type Tone = 'neutral' | 'info' | 'success' | 'warning' | 'danger'
export type Dict = Record<string, string>
