export type Role = 'client' | 'admin' | 'operator' | 'approver'
export type UiMode = 'normal' | 'loading' | 'empty' | 'error'
export type Language = 'zh' | 'en'
export type ModalType = null | 'submitWithdrawal' | 'approveWithdrawal' | 'approveAddress' | 'confirmTrade'
export type Page =
  | 'dashboard'
  | 'kyc'
  | 'accounts'
  | 'account_detail'
  | 'deposit'
  | 'trade'
  | 'orders'
  | 'order_detail'
  | 'withdraw'
  | 'withdraw_submitted'
  | 'withdraw_tracking'
  | 'approvals'
  | 'approval_history'
  | 'address_book'
  | 'add_address'
  | 'address_approval_detail'
  | 'team'
  | 'messages'
  | 'chat'
  | 'trader_dashboard'
  | 'trader_rfq_queue'
  | 'trader_rfq_detail'
  | 'trader_lp_monitor'
  | 'trader_quote_history'
  | 'trader_exception_desk'
  | 'admin_business_dashboard'
  | 'admin_user_management'
  | 'admin_trade_management'
  | 'admin_fund_management'
  | 'admin_risk_management'
  | 'admin_routing_management'
  | 'admin_report_management'
  | 'admin_settings'
  | 'admin_user_detail'
  | 'admin_trade_detail'
  | 'admin_fund_detail'
  | 'admin_risk_detail'
  | 'admin_routing_detail'
  | 'admin_report_detail'
  | 'admin_settings_detail'

export type Tone = 'neutral' | 'info' | 'success' | 'warning' | 'danger'
export type Dict = Record<string, string>
